### ISSUE TITLE
VEP cache/plugin directory option not implemented

### ISSUE THREAD

**Issue by sandain** [ylab-hi/ScanNeo#13]
According to the [README](https://github.com/ylab-hi/ScanNeo/blob/master/README.md#options-1), there is an option to provide the location of the VEP cache/plugin directory for the indels annotation phase. However, this option is not currently implemented:
```
usage: ScanNeo.py [-h] [-v] {indel,anno,hla,fasta} ...
ScanNeo.py: error: unrecognized arguments: -d /mnt/store3/clustcrilab/tools/scanneo/vep/
```
```
usage: ScanNeo.py [-h] [-v] {indel,anno,hla,fasta} ...
ScanNeo.py: error: unrecognized arguments: --dir /mnt/store3/clustcrilab/tools/scanneo/vep/
```

**Comment by dolittle007** [comment]
I have fixed this bug. 56fe1d9
Thanks a lot.

**Comment by sandain** [comment]
Thanks. I was working on a patch, but I'll revert my changes and use yours.
