### ISSUE TITLE
Where can I access the LNCaP RNA-seq data

### ISSUE THREAD

**Issue by indapa** [ylab-hi/ScanNeo#2]
I would like to use the ScanNeo pipeline and would like to reproduce the results described in the [paper](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btz193/5384488)

> To validate our pipeline, we first chose to analyze RNA-Seq data of the LNCaP (ATCC, no. CRL-1740) prostate cancer cell line from Cancer Cell Line Encyclopedia (Barretina et al., 2012) to discover indels and neoantigens with ScanNeo. We identified 48 indels and 58 neoantigens at length 11 AA in the LNCaP cell line (Supplementary Dataset S1). 

But I'm unclear where to get this RNAseq data from as I don't see a SRA identifier or another information about it. Can you kindly clarify where to get this data?

**Comment by dolittle007** [comment]
You may get a copy of RNA-Seq data from GDC Portal.
https://portal.gdc.cancer.gov/legacy-archive/files/7eb8a31a-6d4c-4f2a-bc7a-111ca1d991c8
