### ISSUE TITLE
pysam module not found

### ISSUE THREAD

**Issue by aditisk** [ylab-hi/ScanNeo#3]
Hello, I'm a new user and excited to try out this tool. I am getting an error in the 1st step. I have already installed the pysam module (I can import it via the python command line) however I'm still getting a module not found error. 

`Begin building indel.bam using transIndel
Error happend!: Command 'transIndel_build_RNA.py -r /path/to/hg38.fa -g /path/to/gencode.v21.annotation.gtf -i /zfs1/rferris/adk85/nextflow_test/work/BAMs/R_T_3_ZAN174A7_S30_R1_001Aligned.sortedByCoord.o$
pysam module not found.
Please install it before.
`
I would really appreciate any help/suggestions on fixing this issue. Thanks.

**Comment by dolittle007** [comment]
Please check the first line of transIndel_build_RNA.py, and change #!/usr/bin/python to #!/usr/bin/env python or the python you used installed with pysam (#!/path/to/your_python)
Hope it helps.
Thank you.

**Comment by aditisk** [comment]
Hi @dolittle007, thanks for the suggestion. I was able to get past that error.

I am running into another issue though. Even though I put the correct paths to the fasta and gtf files in my config.ini file, I don't see them being implemented corrected. I even changed the code in the Optitype script to hardcode the path of my ini file. 

`if __name__ == '__main__':

    this_dir = this_dir = os.path.dirname(os.path.realpath(__file__))
    config_default = '/ihome/rferris/adk85/.conda/envs/scanneo/bin/config.ini'
`

I'm attaching the file with the error message here. In Step 4, these are the lines that don't pick up the paths specified in my config file. My config.ini is in the same folder as the scripts.

`Step4: Indexing BWA BAM finished!
transIndel_build_RNA.py -r /path/to/hg38.fa -g /path/to/gencode.v21.annotation.gtf`

How do I fix this ? Thanks for your help in advance. 

[test.pbs.o1093919.txt](https://github.com/ylab-hi/ScanNeo/files/5072093/test.pbs.o1093919.txt)

**Comment by aditisk** [comment]
I was able to solve this by changing the path to the config.ini file in the ScanNeo_utils.py script.
