### ISSUE TITLE
indel.bam not being created

### ISSUE THREAD

**Issue by aditisk** [ylab-hi/ScanNeo#4]
Hi @dolittle007,

I was able to get past the config file error in #3. But I am still getting an error because the indel.bam file is not being created. I am attaching the error file here. In the error file it says that the indel.bam generation is finished but the file is not created.

`Begin building indel.bam using transIndel
finished!
`

Could you please tell me what I need to fix ? Thanks.
[test.pbs.o1094071.txt](https://github.com/ylab-hi/ScanNeo/files/5075945/test.pbs.o1094071.txt)

**Comment by dolittle007** [comment]
Did the file "R_9080_N_ZAN174A16_S54_R1_001Aligned.sortedByCoord.out.bwa.bam" exist?
If it did exist, it could be the problem of transIndel_build.
For debugging purposes, we may have to comment the **remove** function in the ScanNeo.py by adding "#".
Meanwhile I am running more tests on it.

**Comment by aditisk** [comment]
Hi @dolittle007, the .bwa.bam file exists.

I tried to comment the remove function and all calls of that function in the ScanNeo.py but I'm getting the same error again. Is there anything else I can try ?

Please let me know the outcome of your testing. Thanks.

**Comment by dolittle007** [comment]
I tested using different BAM files. There is no problem in my end. It may be a bug in transIndel. Or you input the wrong GTF file, I am guessing. The GTF file and the BAM file should use the same coordinate system. For example, both chr1 ... chrY or both 1 ... Y.
I have contacted the transIndel author, I will update ScanNeo along with transIndel soon.
Thank you!
