### ISSUE TITLE
empty vcf file in step2 anno

### ISSUE THREAD

**Issue by eunjeongcho** [ylab-hi/ScanNeo#5]
Hi. @dolittle007  Thanks for the good program.

I have a question about step2 anno.
As a result of step2, an empty vcf file was created.
I found there was no variant in the pre_vep.44778.vcf file.
The same problem repeats with the "-s" option. 
How can I solve this problem?

my input vcf looks like this. Thanks.

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  input
1       979487  .       A       AG      .       .       NS=1;AO=4;DP=11;AB=0.36;SVLEN=1;SVTYPE=INS;SVMETHOD=transIndel_ALN;CHR2=1;END=979488    GT      1/1
1       983154  .       .       <DEL>   .       .       NS=1;AO=11;DP=11;AB=1.0;SVLEN=1;SVTYPE=DEL;SVMETHOD=transIndel_ALN;CHR2=1;END=983155    GT      1/1
1       1477323 .       .       <DEL>   .       .       NS=1;AO=29;DP=29;AB=1.0;SVLEN=2;SVTYPE=DEL;SVMETHOD=transIndel_ALN;CHR2=1;END=1477325   GT      1/1

**Comment by dolittle007** [comment]
Can you try to run the following command in your bash environment? I assume you are using the GRCh38 reference.

vep --offline --force_overwrite --assembly GRCh38 --input_file **INPUT_VCF** --format vcf --output_file **OUTPUT_VCF** \
        --vcf --symbol --terms SO --af --af_gnomad --plugin Downstream --plugin Wildtype --no_stats`

OR you can set -c 1 when using "ScanNeo anno" to see whether it will output variants or not.
Thank you.

**Comment by eunjeongcho** [comment]
There seems to be a problem with my ref or gtf file, so I downloaded the reference and gtf again from genecode and the problem was solved. Thank you.
