### ISSUE TITLE
 No .bwa.bam generated

### ISSUE THREAD

**Issue by FcoughN** [ylab-hi/ScanNeo#7]
Hi@dolittle007,
thanks for the great work,
I am new to python and I met an error in step 1 ,

`INFO    2021-05-02 21:04:45     MarkDuplicates  Will retain up to 33554432 duplicate indices before spilling to disk.
INFO    2021-05-02 21:04:45     MarkDuplicates  Traversing read pair information and detecting duplicates.
INFO    2021-05-02 21:04:45     SortingCollection       Creating merging iterator from 7 files
INFO    2021-05-02 21:04:58     MarkDuplicates  Traversing fragment information and detecting duplicates.
INFO    2021-05-02 21:04:58     SortingCollection       Creating merging iterator from 14 files
INFO    2021-05-02 21:05:17     MarkDuplicates  Sorting list of duplicate records.
INFO    2021-05-02 21:05:19     MarkDuplicates  After generateDuplicateIndexes freeMemory: 527485280; totalMemory: 806354944; maxMemory: 1073741824
INFO    2021-05-02 21:05:19     MarkDuplicates  Marking 16683374 records as duplicates.
INFO    2021-05-02 21:05:19     MarkDuplicates  Found 351931 optical duplicate clusters.
INFO    2021-05-02 21:05:19     MarkDuplicates  Reads are assumed to be ordered by: unsorted
[Sun May 02 21:05:19 CST 2021] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 6.72 minutes.
Runtime.totalMemory()=806354944
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: This program requires input that are either coordinate or query sorted (according to the header, or at least ASSUME_SORT_ORDER and the content.) Found ASSUME_SORT_ORDER=null and header sortorder=unsorted
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:294)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

Error: No cz4434523.bwa.bam generated!
`

I would really appreciate it  if you can give me some suggestions on fixing this problem.
Thanks.

**Comment by dolittle007** [comment]
Hi@Mt-cn,
"Found ASSUME_SORT_ORDER=null and header sortorder=unsorted"
It seems that your input an unsorted RNA-Seq BAM file, please use SamTools to sort it before feed it to ScanNeo.

**Comment by FcoughN** [comment]
> Hi@Mt-cn,
> "Found ASSUME_SORT_ORDER=null and header sortorder=unsorted"
> It seems that your input an unsorted RNA-Seq BAM file, please use SamTools to sort it before feed it to ScanNeo.

Thank you so much!
