### ISSUE TITLE
transIndel_call.py ,StopIteration

### ISSUE THREAD

**Issue by FcoughN** [ylab-hi/ScanNeo#8]
Hi@dolittle007,
Sorry to bother you again,
I met some problems in tranIndel_call.py,

All is well before: 

```
Step4: Indexing BWA BAM finished!
transIndel_build_RNA.py -r GCF_000001405.39_GRCh38.p13_genomic.fna -g GCF_000001405.39_GRCh38.p13_genomic-NCBI.gtf -i sample_sorted.bwa.bam -o sample_sorted.indel.bam
Begin building indel.bam using transIndel
finished!
```
After that :
```
transIndel_call.py -i sample_sorted.indel.bam -o sample_sorted -d 10 -m 50 -l 1
Begin calling INDELs using transIndel
Error happend!: Command 'transIndel_call.py -i sample_sorted.indel.bam -o sample_sorted -d 10 -m 50 -l 1' returned non-zero exit status 1
transIndel call starts running: 2021-05-05 21:23:20
Traceback (most recent call last):
  File "/mnt/sdb/ScanNeo/transIndel_call.py", line 191, in <module>
    main()
  File "/mnt/sdb/ScanNeo/transIndel_call.py", line 185, in main
    sv_scan(input_bam, output_vcf_prefix, ao_cutoff, dp_cutoff, vaf_cutoff, indel_len_cutoff, target, mapq_cutoff)
  File "/mnt/sdb/ScanNeo/transIndel_call.py", line 75, in sv_scan
    for col in samfile.pileup(region=each_region):
  File "pysam/libcalignmentfile.pyx", line 1344, in pysam.libcalignmentfile.AlignmentFile.pileup
  File "pysam/libcalignmentfile.pyx", line 2667, in pysam.libcalignmentfile.IteratorColumnAllRefs.__cinit__
StopIteration
```
I've checked the The GTF file and the sorted BAM file,and they use the same coordinate system.

Hope that you can give me some suggestion on it.
Thank you so much!

P.S.
When I ran `transIndel_build_RNA.py`,`transIndel_call.py`
I also met:
`ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False`
So I added `check_sq=False` into `transIndel_build_RNA.py` and `transIndel_call.py`.
I don't know whether it caused the problem in `transIndel_call.py`, but I can't find another way to run `transIndel_build_RNA.py` .

Thank you again!

**Comment by GuangShuaiWang** [comment]
hi, I also meet this question.
How do you fix this problems?
